### ISSUE TITLE
Save audio from Telegram to Deep

### ISSUE THREAD

**Issue by SonnyRoot** [deep-foundation/dev#161]
This package should download audio from telegram and save it to deep

**Comment by Konard** [comment]
@Prinz-Eugen-Deep what is the name of your package?

**Comment by Prinz-Eugen-Deep** [comment]
https://www.npmjs.com/package/@deep-foundation/telegram_save_audio

**Comment by Konard** [comment]
Done at https://habr.com/ru/companies/deepfoundation/articles/801137
